import type { SolvePayload } from "@aulas/shared";

export const assignmentRunDemoPayload: SolvePayload = {
  institution_id: "inst_aulaflow_demo",
  academic_period_id: "period_2026_1",
  groups: [
    {
      id: "group_lam_2_m",
      institution_id: "inst_aulaflow_demo",
      academic_period_id: "period_2026_1",
      name: "LAM 2 M",
      size: 47,
      program_id: "lam",
      semester: 2,
      shift: "morning",
      required_room_type: "normal",
      preferred_buildings: ["building_c"],
    },
    {
      id: "group_ing_1_m",
      institution_id: "inst_aulaflow_demo",
      academic_period_id: "period_2026_1",
      name: "Ingles 1 M",
      size: 32,
      program_id: "ingles",
      semester: 1,
      shift: "morning",
      required_room_type: "ingles",
      required_features: ["audio"],
      preferred_buildings: ["building_a"],
    },
    {
      id: "group_psi_5_v",
      institution_id: "inst_aulaflow_demo",
      academic_period_id: "period_2026_1",
      name: "Psicologia 5 V",
      size: 22,
      program_id: "psicologia",
      semester: 5,
      shift: "evening",
      required_room_type: "camara_gesell",
      required_features: ["camara"],
      preferred_buildings: ["building_c"],
    },
    {
      id: "group_mae_1_v",
      institution_id: "inst_aulaflow_demo",
      academic_period_id: "period_2026_1",
      name: "Maestria 1 V",
      size: 28,
      program_id: "maestria",
      semester: 1,
      shift: "evening",
      required_room_type: "maestria",
      preferred_buildings: ["building_b"],
    },
  ],
  rooms: [
    {
      id: "room_1_c",
      institution_id: "inst_aulaflow_demo",
      name: "Aula 1 C",
      capacity: 40,
      building_id: "building_c",
      floor: 0,
      room_type: "normal",
      compatible_room_types: ["normal"],
      features: ["proyector"],
      has_elevator_access: true,
      is_active: true,
      is_reservable: true,
    },
    {
      id: "room_3_c",
      institution_id: "inst_aulaflow_demo",
      name: "Aula 3 C",
      capacity: 60,
      building_id: "building_c",
      floor: 0,
      room_type: "normal",
      compatible_room_types: ["normal"],
      features: ["proyector"],
      has_elevator_access: true,
      is_active: true,
      is_reservable: true,
    },
    {
      id: "room_10_b",
      institution_id: "inst_aulaflow_demo",
      name: "Aula 10 B",
      capacity: 40,
      building_id: "building_b",
      floor: 1,
      room_type: "ingles",
      compatible_room_types: ["ingles"],
      features: ["audio", "proyector"],
      has_elevator_access: true,
      is_active: true,
      is_reservable: true,
      reserved_for_room_types: ["ingles"],
    },
    {
      id: "room_mae_b",
      institution_id: "inst_aulaflow_demo",
      name: "Aula Maestria B",
      capacity: 40,
      building_id: "building_b",
      floor: 1,
      room_type: "maestria",
      compatible_room_types: ["maestria"],
      features: ["mesa_directiva", "proyector"],
      has_elevator_access: true,
      is_active: true,
      is_reservable: true,
      reserved_for_room_types: ["maestria"],
    },
    {
      id: "room_gesell_c",
      institution_id: "inst_aulaflow_demo",
      name: "Camara Gesell C",
      capacity: 40,
      building_id: "building_c",
      floor: 0,
      room_type: "camara_gesell",
      compatible_room_types: ["camara_gesell"],
      features: ["camara", "audio"],
      has_elevator_access: true,
      is_active: true,
      is_reservable: true,
      reserved_for_room_types: ["camara_gesell"],
    },
  ],
  schedules: [
    {
      id: "schedule_lam_monday",
      institution_id: "inst_aulaflow_demo",
      academic_period_id: "period_2026_1",
      group_id: "group_lam_2_m",
      teacher_id: "teacher_ana",
      course_name: "Logistica Administrativa",
      day: "monday",
      start_time: "08:00",
      end_time: "10:00",
      expected_students: 47,
      required_room_type: "normal",
      preferred_buildings: ["building_c"],
    },
    {
      id: "schedule_ingles_tuesday",
      institution_id: "inst_aulaflow_demo",
      academic_period_id: "period_2026_1",
      group_id: "group_ing_1_m",
      teacher_id: "teacher_victor",
      course_name: "Ingles I",
      day: "tuesday",
      start_time: "08:00",
      end_time: "10:00",
      expected_students: 32,
      required_room_type: "ingles",
      required_features: ["audio"],
      preferred_buildings: ["building_a"],
    },
    {
      id: "schedule_psicologia_friday",
      institution_id: "inst_aulaflow_demo",
      academic_period_id: "period_2026_1",
      group_id: "group_psi_5_v",
      teacher_id: "teacher_lucia",
      course_name: "Practica de Observacion",
      day: "friday",
      start_time: "16:00",
      end_time: "18:00",
      expected_students: 22,
      required_room_type: "camara_gesell",
      required_features: ["camara"],
      preferred_buildings: ["building_c"],
    },
    {
      id: "schedule_maestria_wednesday",
      institution_id: "inst_aulaflow_demo",
      academic_period_id: "period_2026_1",
      group_id: "group_mae_1_v",
      teacher_id: "teacher_victor",
      course_name: "Seminario Directivo",
      day: "wednesday",
      start_time: "18:00",
      end_time: "20:00",
      expected_students: 28,
      required_room_type: "maestria",
      preferred_buildings: ["building_b"],
    },
  ],
  current_assignments: [
    {
      institution_id: "inst_aulaflow_demo",
      schedule_id: "schedule_lam_monday",
      group_id: "group_lam_2_m",
      room_id: "room_1_c",
      status: "proposed",
    },
    {
      institution_id: "inst_aulaflow_demo",
      schedule_id: "schedule_ingles_tuesday",
      group_id: "group_ing_1_m",
      room_id: "room_10_b",
      status: "proposed",
    },
    {
      institution_id: "inst_aulaflow_demo",
      schedule_id: "schedule_maestria_wednesday",
      group_id: "group_mae_1_v",
      room_id: "room_mae_b",
      status: "proposed",
    },
  ],
  rules: [
    {
      code: "room_time_conflict",
      name: "Sin doble uso de aula",
      rule_type: "mandatory",
      severity: "hard",
      is_enabled: true,
    },
    {
      code: "capacity_required",
      name: "Capacidad suficiente",
      rule_type: "mandatory",
      severity: "hard",
      is_enabled: true,
    },
    {
      code: "room_blocked",
      name: "Aula bloqueada",
      rule_type: "mandatory",
      severity: "hard",
      is_enabled: true,
    },
    {
      code: "capacity_fit",
      name: "Ajuste de capacidad",
      rule_type: "preference",
      severity: "warning",
      is_enabled: true,
      weight: 10,
    },
  ],
  teacher_constraints: [
    {
      teacher_id: "teacher_ana",
      requires_ground_floor: true,
      avoid_long_transfers: true,
      max_transfer_distance_meters: 250,
    },
    {
      teacher_id: "teacher_lucia",
      requires_ground_floor: true,
      required_room_features: ["camara"],
    },
  ],
  room_blocks: [
    {
      room_id: "room_3_c",
      academic_period_id: "period_2026_1",
      day: "friday",
      start_time: "08:00",
      end_time: "10:00",
      reason: "Mantenimiento preventivo",
      is_active: true,
    },
  ],
  building_distances: [
    {
      from_building_id: "building_a",
      to_building_id: "building_b",
      distance_meters: 180,
    },
    {
      from_building_id: "building_a",
      to_building_id: "building_c",
      distance_meters: 420,
    },
    {
      from_building_id: "building_b",
      to_building_id: "building_c",
      distance_meters: 300,
    },
  ],
  constraints: {
    capacity_waste_warning_ratio: 0.45,
    large_room_waste_ratio: 0.72,
    default_max_transfer_distance_meters: 350,
  },
};

