import type { SolvePayload } from "@aulas/shared";

export const demoPayload: SolvePayload = {
  institution_id: "inst_demo",
  groups: [
    {
      id: "grp_derecho_1a",
      institution_id: "inst_demo",
      name: "Derecho 1A",
      size: 42,
      program_id: "derecho",
      semester: 1,
      required_room_type: "normal",
      preferred_buildings: ["edificio_a"],
    },
    {
      id: "grp_sistemas_3b",
      institution_id: "inst_demo",
      name: "Sistemas 3B",
      size: 28,
      program_id: "sistemas",
      semester: 3,
      required_room_type: "computo",
      required_features: ["computadoras"],
      preferred_buildings: ["edificio_b"],
    },
    {
      id: "grp_psicologia_5a",
      institution_id: "inst_demo",
      name: "Psicologia 5A",
      size: 18,
      program_id: "psicologia",
      semester: 5,
      required_room_type: "camara_gesell",
      preferred_buildings: ["edificio_c"],
    },
    {
      id: "grp_maestria_1",
      institution_id: "inst_demo",
      name: "Maestria Ejecutiva",
      size: 22,
      program_id: "maestria",
      semester: 1,
      required_room_type: "maestria",
      preferred_buildings: ["edificio_a"],
    },
  ],
  rooms: [
    {
      id: "room_a101",
      institution_id: "inst_demo",
      name: "A-101",
      capacity: 45,
      building_id: "edificio_a",
      floor: 0,
      room_type: "normal",
      compatible_room_types: ["normal", "maestria"],
      features: ["planta_baja", "proyector"],
      has_elevator_access: true,
      is_active: true,
    },
    {
      id: "room_a201",
      institution_id: "inst_demo",
      name: "A-201",
      capacity: 60,
      building_id: "edificio_a",
      floor: 1,
      room_type: "auditorio",
      compatible_room_types: ["auditorio", "normal"],
      features: ["proyector", "audio"],
      has_elevator_access: false,
      is_active: true,
    },
    {
      id: "room_b202",
      institution_id: "inst_demo",
      name: "B-202",
      capacity: 32,
      building_id: "edificio_b",
      floor: 1,
      room_type: "computo",
      compatible_room_types: ["computo"],
      features: ["computadoras", "proyector"],
      has_elevator_access: true,
      is_active: true,
    },
    {
      id: "room_c010",
      institution_id: "inst_demo",
      name: "C-010",
      capacity: 20,
      building_id: "edificio_c",
      floor: 0,
      room_type: "camara_gesell",
      compatible_room_types: ["camara_gesell"],
      features: ["camara", "audio", "planta_baja"],
      has_elevator_access: true,
      is_active: true,
    },
  ],
  schedules: [
    {
      id: "sch_derecho_lun_08",
      institution_id: "inst_demo",
      group_id: "grp_derecho_1a",
      teacher_id: "teacher_ana",
      day: "monday",
      start_time: "08:00",
      end_time: "10:00",
      expected_students: 42,
    },
    {
      id: "sch_sistemas_lun_08",
      institution_id: "inst_demo",
      group_id: "grp_sistemas_3b",
      teacher_id: "teacher_omar",
      day: "monday",
      start_time: "08:00",
      end_time: "10:00",
      expected_students: 30,
      required_room_type: "computo",
      required_features: ["computadoras"],
    },
    {
      id: "sch_psicologia_mar_10",
      institution_id: "inst_demo",
      group_id: "grp_psicologia_5a",
      teacher_id: "teacher_lucia",
      day: "tuesday",
      start_time: "10:00",
      end_time: "12:00",
      expected_students: 18,
      required_room_type: "camara_gesell",
    },
    {
      id: "sch_maestria_mar_18",
      institution_id: "inst_demo",
      group_id: "grp_maestria_1",
      teacher_id: "teacher_ana",
      day: "tuesday",
      start_time: "18:00",
      end_time: "20:00",
      expected_students: 22,
      required_room_type: "maestria",
    },
  ],
  constraints: {
    teacher_constraints: [
      {
        teacher_id: "teacher_ana",
        requires_ground_floor: true,
        requires_elevator: false,
        avoid_long_transfers: true,
        max_transfer_distance_meters: 260,
      },
      {
        teacher_id: "teacher_lucia",
        requires_ground_floor: true,
      },
    ],
    room_blocks: [
      {
        room_id: "room_a201",
        day: "monday",
        start_time: "07:00",
        end_time: "11:00",
        reason: "Evento institucional",
      },
    ],
    room_reservations: [
      {
        room_id: "room_c010",
        day: "tuesday",
        start_time: "09:00",
        end_time: "13:00",
        reserved_for_room_types: ["camara_gesell"],
        note: "Uso reservado para practica supervisada",
      },
    ],
    building_distances: [
      {
        from_building_id: "edificio_a",
        to_building_id: "edificio_b",
        distance_meters: 180,
      },
      {
        from_building_id: "edificio_a",
        to_building_id: "edificio_c",
        distance_meters: 420,
      },
      {
        from_building_id: "edificio_b",
        to_building_id: "edificio_c",
        distance_meters: 300,
      },
    ],
    capacity_waste_warning_ratio: 0.45,
    large_room_waste_ratio: 0.72,
    default_max_transfer_distance_meters: 350,
  },
};

